---
- name: playbook to download a jar file
  hosts: localhost
  become: yes
  tasks:
    - name: check jar file exists or not
      stat:
        path: /opt/mysql-connector-java-8.0.26.jar
      register: jar_output
    - name: print jar-file-existence-output
      debug:
        msg: "{{ jar_output }}"
    - name: download jar file
      get_url:
        url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar
        dest: /opt
        mode: '0755'
      when: not jar_output.stat.exists
